enableStrictSsl: false

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '*'
  '@graphile/pg-aggregates@*':
    peerDependencies:
      tslib: '*'
  '@graphql-codegen/typescript-react-apollo@*':
    dependencies:
      graphql-tag: '*'
  '@mui/base@*':
    dependencies:
      csstype: '*'
  '@mui/styled-engine@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      csstype: '*'
  '@mui/x-data-grid-pro@*':
    dependencies:
      '@mui/base': latest
      '@mui/system': '*'
      react-dom: '*'
  '@mui/x-data-grid@*':
    dependencies:
      react-dom: '*'
  '@mui/x-date-pickers@*':
    dependencies:
      react-dom: '*'
  cosmiconfig-typescript-loader@*:
    dependencies:
      '@types/node': '*'
      typescript: '*'
  eslint-config-react-app@*:
    dependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  graphile-build-pg@*:
    peerDependencies:
      graphql: '*'
  react-dev-utils@*:
    dependencies:
      typescript: '*'
      webpack: '*'
  react-scripts@*:
    dependencies:
      autoprefixer: '*'
      worker-loader: '*'
  worker-loader@*:
    dependencies:
      webpack: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
      jest-runtime: '*'
  '@cspotcode/source-map-support@*':
    dependencies:
      source-map-support: '*'
  jest-cli@*:
    dependencies:
      '@jest/reporters': '*'
      '@jest/console': '*'
  '@testing-library/react@*':
    dependencies:
      '@testing-library/dom': '*'
  '@testing-library/user-event@*':
    dependencies:
      '@testing-library/dom': '*'


yarnPath: .yarn/releases/yarn-3.2.0.cjs
